# Generated by Django 5.0.2 on 2024-02-20 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0002_employeemodel_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='Roomtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_app.roomtypemodel'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='floorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_app.floor'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='roomid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_app.roommodel'),
        ),
    ]
