# Generated by Django 5.0.2 on 2024-02-20 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0003_employeemodel_roomtype_employeemodel_floorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='flatid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_app.flat'),
        ),
    ]
