# Generated by Django 5.0.2 on 2024-02-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0005_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='usertype',
        ),
    ]
