# Generated by Django 5.0.2 on 2024-02-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0006_remove_login_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequestmodel',
            name='employeeid',
        ),
    ]
