# Generated by Django 5.0.2 on 2024-02-20 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0007_remove_leaverequestmodel_employeeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestmodel',
            name='employeeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_app.employeemodel'),
        ),
    ]
