# Generated by Django 5.0.2 on 2024-02-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0009_remove_leaverequestmodel_approvalstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintmodel',
            name='employeeid',
        ),
    ]
