# Generated by Django 5.0.2 on 2024-02-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0010_remove_complaintmodel_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintmodel',
            name='complaint_against',
        ),
    ]
