# Generated by Django 5.0.2 on 2024-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0011_remove_complaintmodel_complaint_against'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmodel',
            name='complaint_against',
            field=models.CharField(default='', max_length=100),
        ),
    ]
