# Generated by Django 3.2 on 2024-02-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0013_complaintmodel_employeeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
