# Generated by Django 5.0.2 on 2024-02-21 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0014_itemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='totalNoOfLeave',
            field=models.IntegerField(default='30'),
        ),
        migrations.AddField(
            model_name='login',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_app.employeemodel'),
        ),
    ]
