# Generated by Django 5.0.2 on 2024-02-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0015_employeemodel_totalnoofleave_login_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestmodel',
            name='approvalstatus',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='leaverequestmodel',
            name='numberofdays',
            field=models.IntegerField(),
        ),
    ]
