# Generated by Django 3.2 on 2024-02-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0016_leaverequestmodel_approvalstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportationmodel',
            old_name='campid',
            new_name='campname',
        ),
        migrations.RemoveField(
            model_name='transportationmodel',
            name='busname',
        ),
        migrations.AddField(
            model_name='transportationmodel',
            name='busno',
            field=models.IntegerField(default='1'),
        ),
    ]
